### PR TITLE
Updated layout to make books larger

### PR DESCRIPTION
**Pull request by nihal111**
This simply increases the dimensions of the books so that they look a lot better.

### CODE REVIEW

**Comment by Waterpicker** [comment]
Can you scale up the text a bit? The text looks a bit small on the new size.

**Comment by Waterpicker** [comment]
I've decided the text size is fine. Thanks for correcting the gui size. ^^

**Comment by nihal111** [comment]
@Waterpicker Sorry for not replying earlier. The text size change would've required a change in UIText.
I'm also attempting to rewrite the whole module such that it becomes similar to Journals (i.e. uses BrowserWidget) facilitating easy use of images, change of font etc.

**Comment by Waterpicker** [comment]
Alright. We should chat sometime so I can get up to speed with what you have planned. :3

**Comment by nihal111** [comment]
@Waterpicker, ehh.. I just went ahead and made a few big changes on my own :stuck_out_tongue: Have a look at #14

**Pull request merged**
