### PR TITLE
Bookcases now accept only books.

### LINKED ISSUE #5: Re-implement some unique functionality for bookcases
Way back in the olden days, in the time before time, bookcases had a filter on what items they would accept (only books, naturally). This was removed over time as the engine matured, and we might not have the original event anymore.

Mentioned briefly with more details at the bottom of #2

### PR DESCRIPTION
**Pull request by arpan98**
Fixes #5 .
Added a check that when the target inventory slot has a BookCaseComponent, the item must have a BookComponent.

### CODE REVIEW

**Comment by iojw** [comment]
Just wanted to let you know that you can put something like `BookcaseComponent bookcaseComponent` as part of the parameters in the function to filter it such that the event function only gets called if the entity contains that component. It's equivalent to `if (entity.hasComponent(BookcaseComponent.class))`. The variable also gets filled automatically so it's useful when you want to filter a function by more than one component and access those components as well.

**Comment by arpan98** [comment]
Agreed, and changed.

**Comment by Waterpicker** [comment]
I had to manually merged the commits in but they work.

**Comment by Waterpicker** [comment]
Thank you for the PR.

**Comment by Cervator** [comment]
Looks like the merge had just ended up duplicating something over the conflict. All fixed now :-)

Nice work!

**Comment by arpan98** [comment]
Oops! Sorry for that! Having two different PR's for the same file is not a good idea, will remember that in the future :-)

**Comment by Waterpicker** [comment]
Nothing wrong with that. Nice to see the module getting some love after so many month after my overhaul.

**Pull request merged**
